version: '3'

services:
  #  oracle_db:
  #    image: oracleinanutshell/oracle-xe-11g:latest
  #    restart: always
  #    ports:
  #      - 1521:1521
  #      - 5500:5500
  #    volumes:
  #      - /data/db:/data/db

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ../backend:/app
#      - /data/backend/storage:/data/backend
    links:
      - summarizer
    depends_on:
      - summarizer
  #    environment:
  #      - ORACLE_CONNECT_STRING='0.0.0.0:1521'

  summarizer:
    build:
      context: ../summarizer
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /data/summarizer/storage:/data/summarizer

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    links:
      - backend
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/app/src

      #    volumes:
#      - ./frontend:/app/frontend
#      - /app/node_modules
#      - ./frontend:/app

networks:
  default:
    external:
      name: local_network_1
